/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CharactersPanel: typeof import('./src/components/RightToolbar/CharactersPanel.vue')['default']
    EditorToolbar: typeof import('./src/components/Editor/EditorToolbar.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElCarousel: typeof import('element-plus/es')['ElCarousel']
    ElCarouselItem: typeof import('element-plus/es')['ElCarouselItem']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElColorPicker: typeof import('element-plus/es')['ElColorPicker']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSlider: typeof import('element-plus/es')['ElSlider']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ImageInsert: typeof import('./src/components/Editor/ImageInsert.vue')['default']
    ImageLibrary: typeof import('./src/components/Editor/ImageLibrary.vue')['default']
    OutlinePanel: typeof import('./src/components/RightToolbar/OutlinePanel.vue')['default']
    PreviewPanel: typeof import('./src/components/RightToolbar/PreviewPanel.vue')['default']
    ProofreadPanel: typeof import('./src/components/RightToolbar/ProofreadPanel.vue')['default']
    RightToolbar: typeof import('./src/components/RightToolbar/RightToolbar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingsPanel: typeof import('./src/components/RightToolbar/SettingsPanel.vue')['default']
    SpellCheckPanel: typeof import('./src/components/RightToolbar/SpellCheckPanel.vue')['default']
    UserInfo: typeof import('./src/components/UserInfo.vue')['default']
  }
}
